language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/taxi_trips

node_js:  
  - 12

before_script:
  - psql -c 'create database  taxi_trips;' -U postgres
  - psql -U postgres -d taxi_trips -a -f data.sql
  - psql -U postgres -d taxi_trips -a -f tables.sql

services:
  - postgresql